sonar.organization=1-family-tree
sonar.projectKey=family_tree_api_key
sonar.projectName=Family Tree API

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=**/*.spec.ts,**/*.test.ts,**/node_modules/**,**/dist/**,src/test/**

sonar.javascript.lcov.reportPaths=../../coverage/apps/api/lcov.info
sonar.typescript.tsconfigPath=tsconfig.app.json
sonar.sourceEncoding=UTF-8
